### ISSUE TITLE
想得到您的数据

### ISSUE THREAD

**Issue by HBUhss** [Xiaoyinggit/DCRS#1]
你好，我非常想要得到您的数据。我想跑通这个代码，但是它说找不到这个文件，可以发一份吗，非常感谢
12197@DESKTOP-RQIC9IK MINGW64 /e/proposal/paper2/DCRS-main/code
$ /bin/sh E:/proposal/paper2/DCRS-main/code/run.sh
args: Namespace(DCRSPara={'0': 0.0}, activation_function='relu', batch_norm=1, batch_size=128, data_path='../data/', dataset='ml_1m', dropout='[0.5, 0.2]', epochs=300, gpu='
0', hidden_factor=64, lamda=0.1, layers='[64]', lr=0.05, model='DCRS', model_path='./saved_models/', num_groups=18, num_user_features=5, optimizer='Adagrad', out=True, topN=
'[10,20]')
Traceback (most recent call last):
  File "main.py", line 127, in <module>
    user_feature, item_feature, num_features, num_UF, num_IF, num_users, num_items, feature_map = data_utils.map_features(user_feature_path, item_feature_path)
  File "E:\proposal\paper2\DCRS-main\code\data_utils.py", line 101, in map_features
    user_feature, item_feature, features = read_user_item_features(user_feature_path, item_feature_path,  features)
  File "E:\proposal\paper2\DCRS-main\code\data_utils.py", line 11, in read_user_item_features
    user_file = np.load(user_file_path, allow_pickle=True).item()
  File "D:\Users\12197\anaconda3\envs\tor\lib\site-packages\numpy\lib\npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '../data/ml_1m/user_feature_file.npy'

**Comment by Xiaoyinggit** [comment]
感谢指出这个bug=。=

data link 已更新： https://drive.google.com/file/d/1euR5fkTjlSKhl92M01GBW8bNxeplweGJ/view?usp=share_link

**Comment by HBUhss** [comment]
很抱歉又来麻烦您，我在国内登不上gooledrive
